name: Lint

on: [pull_request]

jobs:
  e2e-and-unit:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Lints with solium
        run: yarn lint
